import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/headers/Topbar";
import { ThemeContextProvider } from "@/components/contexts/ThemeContextProvider";
import { inter } from "@/lib/utils";
import ContextProviders from "@/components/contexts/ContextProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-8 pt-4`}>
        <ContextProviders>
          <Topbar />
          <main className="">{children}</main>
        </ContextProviders>
      </body>
    </html>
  );
}
