import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/headers/Topbar";
import { inter } from "@/lib/utils";
import ContextProviders from "@/components/contexts/ContextProviders";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-96 px-8 `}>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <ContextProviders>
          <div className="h-screen flex flex-col">
            <Topbar />
            <main className="grow">{children}</main>
          </div>
        </ContextProviders>
      </body>
    </html>
  );
}
