import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/headers/Topbar";
import { ThemeContextProvider } from "@/components/contexts/ThemeContextProvider";
import { inter } from "@/lib/utils";
import ContextProviders from "@/components/contexts/ContextProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-96 px-8 `}>
        <ContextProviders>
          <div className="h-screen flex flex-col">
            <Topbar />
            <main className="grow">{children}</main>
          </div>
        </ContextProviders>
      </body>
    </html>
  );
}
